project_id = "vzcgychqqihqqbcfphya"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.third_party.clerk]
enabled = true
domain = "clerk.snapsketch.mfpeasy.com.au"

[functions.search-projects]
enabled = true
verify_jwt = false
entrypoint = "./functions/search-projects/index.ts"

[functions.update-project-status]
enabled = true
verify_jwt = false
entrypoint = "./functions/update-project-status/index.ts"

[functions.update-project-owner]
enabled = true
verify_jwt = false
entrypoint = "./functions/update-project-owner/index.ts"

[functions.verify-sso]
enabled = true
verify_jwt = false
entrypoint = "./functions/verify-sso/index.ts"

[functions.poolify-proxy]
enabled = true
verify_jwt = false
entrypoint = "./functions/poolify-proxy/index.ts"
